### ISSUE TITLE
Is it possible to explicitly set black version in pre-commit?

### ISSUE THREAD

**Issue by max-sixty** [keewis/blackdoc#122]
Quoting https://github.com/pydata/xarray/pull/6290#issuecomment-1046291891

> FYI something that's a bit surprising is that blackdoc passes in pre-commit locally but not in pre-commit.ci. My guess is that it doesn't specify the version of black it uses and so on my local machine it has an older version of black. I'm not sure whether that's possible with additional_dependencies...

Again — thank you for the excellent tool!

**Comment by keewis** [comment]
this should definitely be possible, but I'm not quite sure where to put it. I would probably suggest to do that in the project's `.pre-commit-config.yaml`:
```yaml
repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black

- repo: https://github.com/keewis/blackdoc
  rev: v0.3.4
  hooks:
  - id: blackdoc
    additional_dependencies: ["black==22.1.0"]
  - id: sync-black-version
```
where the `sync-black-version` hook will keep it in sync with the hook version of `black`. That way, I won't have to release a new version every time `black` does (although that might be better given that `blackdoc` is using some of the internal API of `black`).
